### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by RucaLove** [RucaLove/Q3Project#13]

**Comment by RucaLove** [comment]
1. Who is the user?
2. What does the user need to be able to do?
3. How does the user accomplish this?

**Comment by christiantaggart** [comment]
Users can post pictures of their form looking for advice from more experienced yoga practitioners.
Other users can comment on their picture/post with advice or form correction.
Other users can like their picture/post signifying that it is fine/good.
Verified users (Professionals/ Moderators) can validate good feedback left by others.
Verified users (Professionals/ Moderators) can reply with feedback on form correction.
Users can view other posts asking for advice on form.
