### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by djamesjones4** [RucaLove/Q3Project#7]
Create a db schema

**Comment by Sadaums** [comment]
currently drawing up relations for tables

**Comment by Sadaums** [comment]
have table relationship rough draft done

**Comment by Sadaums** [comment]
https://www.draw.io/#HRucaLove%2FQ3Project%2Fmaster%2FQ3Project

**Comment by Sadaums** [comment]
https://www.draw.io/#HRucaLove%2FQ3Project%2Fmaster%2FQ3Project

**Comment by Sadaums** [comment]
have rough draft of tables, columns for tables

**Comment by Sadaums** [comment]
https://files.slack.com/files-pri/T1T555TL0-F5FQV9AJZ/img_20170519_115258.jpg
